version: '2'
services:
  consul:
    image: gliderlabs/consul-server:latest
    container_name: consul
    command: "-server -bootstrap"
    ports:
      - 8500:8500
    networks:
      - 2immerse

  registrator:
    image: gliderlabs/registrator:v7
    container_name: registrator
    command: "consul://consul:8500"
    depends_on:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    networks:
      - 2immerse

  mongo:
    image: mongo:latest
    container_name: mongo
    depends_on:
      - registrator
    ports:
      - 27017:27017
    networks:
      2immerse:
        aliases:
          - mongo.service.consul

  auth:
    build .
    container_name: auth-service
    command: "-debug"
    depends_on:
      - registrator
      - mongo
    ports:
      - 3000:3000
      - 8080:8080
    environment:
      CONSUL_HTTP_ADDR: consul:8500
      MONGODB_SERVICE: mongo
    networks:
      - 2immerse

networks:
  2immerse:
    driver: bridge
